---
version: '2'
services:

  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - db_container_default
      - kafka_client_default
    environment:
      KAFKA_BROKER: broker:29092
      KAFKA_TOPIC_NAME: ${KAFKA_TOPIC_NAME}
      DB_MYSQL_USER: ${DB_MYSQL_REMOTE_USER}
      DB_MYSQL_ADDRESS: db:3306
      DB_MYSQL_PASS: ${DB_MYSQL_PASS}
networks:
  db_container_default:
    external: true
  kafka_client_default:
    external: true